/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class JNITest */

#ifndef _Included_JNITest
#define _Included_JNITest
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_JNITest_InitHwnd(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_JNITest_Shutdown(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_JNITest_SendCMD(JNIEnv *, jobject, jstring);
JNIEXPORT jint JNICALL Java_JNITest_SendCMDRecvInt(JNIEnv *, jobject, jstring);
JNIEXPORT jstring JNICALL Java_JNITest_SendCMDRecvText(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
